name: Download CPC Product Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - add-product-classification

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run download script
        run: |
          mkdir -p downloads
          python download_vehicle_oil.py
        env: {}

      - name: Upload downloads artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpc-downloads
          path: downloads